/*
Copyright 2026 Adobe. All rights reserved.
This file is licensed to you under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License. You may obtain a copy
of the License at http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under
the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
OF ANY KIND, either express or implied. See the License for the specific language
governing permissions and limitations under the License.
*/

//! Golden parity tests: evaluate upstream Conformulator fixtures through our
//! Rust json-formula evaluator and assert trait outcomes match the Python
//! reference output.
//!
//! Fixtures live in `testfiles/rubrics/goldens/` and were generated by the
//! Python reference evaluator (`c2pa_conformance_rubric_evaluator.py`).
//! Each fixture triple:
//!   - `<name>.json`              - crJSON input
//!   - `<name>.conformance.json`  - expected conformance rubric output
//!   - `<name>.signals.json`      - expected signals rubric output

mod common;

use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};

use profile_evaluator_rs::{load_profile_from_yaml_str, evaluate_rubric_conformance, evaluate_rubric_signals};
use serde_json::Value;

fn goldens_dir() -> PathBuf {
    common::testfiles_dir().join("rubrics/goldens")
}

fn rubric_conformance_path() -> PathBuf {
    common::testfiles_dir()
        .join("rubrics/asset-rubric-conformance0.1-spec2.2.yml")
}

fn rubric_signals_path() -> PathBuf {
    common::testfiles_dir()
        .join("rubrics/asset-rubric-signals-local.yml")
}

/// Discover fixture names by looking for `<name>.json` files with companion
/// `.conformance.json` and `.signals.json` siblings.
fn discover_fixtures() -> Vec<String> {
    let dir = goldens_dir();
    if !dir.exists() {
        return vec![];
    }
    let all: Vec<String> = fs::read_dir(&dir)
        .expect("read goldens dir")
        .filter_map(|e| e.ok())
        .map(|e| e.file_name().to_string_lossy().to_string())
        .collect();

    let all_set: std::collections::HashSet<String> = all.iter().cloned().collect();

    let mut names: Vec<String> = all
        .iter()
        .filter(|f| {
            f.ends_with(".json")
                && !f.ends_with(".conformance.json")
                && !f.ends_with(".signals.json")
        })
        .map(|f| f.trim_end_matches(".json").to_string())
        .filter(|name| {
            all_set.contains(&format!("{name}.conformance.json"))
                && all_set.contains(&format!("{name}.signals.json"))
        })
        .collect();
    names.sort();
    names
}

fn load_json(path: &Path) -> Value {
    let text = fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", path.display()));
    serde_json::from_str(&text)
        .unwrap_or_else(|e| panic!("failed to parse {}: {e}", path.display()))
}

/// Build a trait -> (bucket, reportText) map from conformance output.
fn trait_index(output: &Value) -> HashMap<String, (String, String)> {
    let mut map = HashMap::new();
    for bucket in &["true", "false"] {
        if let Some(categories) = output.get(*bucket).and_then(Value::as_object) {
            for (_category, traits) in categories {
                if let Some(arr) = traits.as_array() {
                    for entry in arr {
                        let trait_name = entry
                            .get("trait")
                            .and_then(Value::as_str)
                            .unwrap_or("")
                            .to_string();
                        let report_text = entry
                            .get("reportText")
                            .and_then(Value::as_str)
                            .unwrap_or("")
                            .to_string();
                        map.insert(trait_name, (bucket.to_string(), report_text));
                    }
                }
            }
        }
    }
    map
}

// ── Conformance parity ──────────────────────────────────────────────

#[test]
fn conformance_golden_parity() {
    let fixtures = discover_fixtures();
    assert!(
        fixtures.len() >= 15,
        "expected at least 15 golden fixtures, found {}",
        fixtures.len()
    );

    let rubric_text = fs::read_to_string(rubric_conformance_path())
        .expect("read conformance rubric");
    let rubric = load_profile_from_yaml_str(&rubric_text, None).expect("compile conformance rubric");

    // Known divergences we track but don't fail on:
    // 1. Our rubric has `no_dst_for_opened_action` which predates the fixtures (EXTRA)
    let known_outcome_bugs: Vec<(&str, &str)> = vec![];
    let known_text_bugs: Vec<(&str, &str)> = vec![];

    let mut total_mismatches = 0;
    let mut mismatch_details: Vec<String> = Vec::new();

    for name in &fixtures {
        let input = load_json(&goldens_dir().join(format!("{name}.json")));
        let expected = load_json(&goldens_dir().join(format!("{name}.conformance.json")));

        let result = evaluate_rubric_conformance(&rubric, &input)
            .unwrap_or_else(|e| panic!("{name}: rubric evaluation failed: {e}"));

        // Verify rubric name and version
        assert_eq!(
            result.get("rubricName").and_then(Value::as_str),
            expected.get("rubricName").and_then(Value::as_str),
            "{name}: rubricName mismatch"
        );
        assert_eq!(
            result.get("rubricVersion").and_then(Value::as_str),
            expected.get("rubricVersion").and_then(Value::as_str),
            "{name}: rubricVersion mismatch"
        );

        let expected_traits = trait_index(&expected);
        let got_traits = trait_index(&result);

        for (trait_name, (want_bucket, want_text)) in &expected_traits {
            let is_known_outcome =
                known_outcome_bugs.contains(&(name.as_str(), trait_name.as_str()));
            let is_known_text =
                known_text_bugs.contains(&(name.as_str(), trait_name.as_str()));

            match got_traits.get(trait_name) {
                None => {
                    mismatch_details.push(format!(
                        "{name}: MISSING trait '{trait_name}' (expected {want_bucket})"
                    ));
                    total_mismatches += 1;
                }
                Some((got_bucket, got_text)) => {
                    if got_bucket != want_bucket {
                        if is_known_outcome {
                            eprintln!(
                                "KNOWN BUG: {name}/{trait_name} outcome {want_bucket}->{got_bucket}"
                            );
                        } else {
                            mismatch_details.push(format!(
                                "{name}: OUTCOME '{trait_name}' expected={want_bucket} got={got_bucket}"
                            ));
                            total_mismatches += 1;
                        }
                    } else if got_text != want_text && !is_known_text {
                        mismatch_details.push(format!(
                            "{name}: TEXT '{trait_name}'\n  want: {want_text}\n  got:  {got_text}"
                        ));
                        total_mismatches += 1;
                    }
                }
            }
        }
    }

    if total_mismatches > 0 {
        panic!(
            "Conformance golden parity: {total_mismatches} unexpected mismatch(es):\n{}",
            mismatch_details.join("\n")
        );
    }
}

// ── Signals parity ──────────────────────────────────────────────────

#[test]
fn signals_golden_parity() {
    let fixtures = discover_fixtures();
    assert!(
        fixtures.len() >= 15,
        "expected at least 15 golden fixtures, found {}",
        fixtures.len()
    );

    let rubric_text =
        fs::read_to_string(rubric_signals_path()).expect("read signals rubric");
    let rubric = load_profile_from_yaml_str(&rubric_text, None).expect("compile signals rubric");

    let mut total_mismatches = 0;
    let mut mismatch_details: Vec<String> = Vec::new();

    for name in &fixtures {
        let input = load_json(&goldens_dir().join(format!("{name}.json")));
        let expected = load_json(&goldens_dir().join(format!("{name}.signals.json")));

        let result = evaluate_rubric_signals(&rubric, &input)
            .unwrap_or_else(|e| panic!("{name}: signals evaluation failed: {e}"));

        // Verify rubric name and version
        assert_eq!(
            result.get("rubricName").and_then(Value::as_str),
            expected.get("rubricName").and_then(Value::as_str),
            "{name}: rubricName mismatch"
        );

        let expected_manifests = expected
            .get("manifests")
            .and_then(Value::as_array)
            .cloned()
            .unwrap_or_default();
        let got_manifests = result
            .get("manifests")
            .and_then(Value::as_array)
            .cloned()
            .unwrap_or_default();

        if expected_manifests.len() != got_manifests.len() {
            mismatch_details.push(format!(
                "{name}: manifest count expected={} got={}",
                expected_manifests.len(),
                got_manifests.len()
            ));
            total_mismatches += 1;
            continue;
        }

        for (i, (want, got)) in expected_manifests
            .iter()
            .zip(got_manifests.iter())
            .enumerate()
        {
            let prefix = format!("{name}[{i}]");

            // assertedBy
            if want.get("assertedBy") != got.get("assertedBy") {
                mismatch_details.push(format!(
                    "{prefix} assertedBy: want={} got={}",
                    want.get("assertedBy").unwrap_or(&Value::Null),
                    got.get("assertedBy").unwrap_or(&Value::Null),
                ));
                total_mismatches += 1;
            }

            // mimeType
            if want.get("mimeType") != got.get("mimeType") {
                mismatch_details.push(format!(
                    "{prefix} mimeType: want={:?} got={:?}",
                    want.get("mimeType"),
                    got.get("mimeType"),
                ));
                total_mismatches += 1;
            }

            // allActionsIncluded
            if want.get("allActionsIncluded") != got.get("allActionsIncluded") {
                mismatch_details.push(format!(
                    "{prefix} allActionsIncluded: want={:?} got={:?}",
                    want.get("allActionsIncluded"),
                    got.get("allActionsIncluded"),
                ));
                total_mismatches += 1;
            }

            // localInceptions
            if want.get("localInceptions") != got.get("localInceptions") {
                mismatch_details.push(format!(
                    "{prefix} localInceptions:\n  want: {}\n  got:  {}",
                    serde_json::to_string_pretty(
                        want.get("localInceptions").unwrap_or(&Value::Null)
                    )
                    .unwrap(),
                    serde_json::to_string_pretty(
                        got.get("localInceptions").unwrap_or(&Value::Null)
                    )
                    .unwrap(),
                ));
                total_mismatches += 1;
            }

            // localTransformations
            if want.get("localTransformations") != got.get("localTransformations") {
                mismatch_details.push(format!(
                    "{prefix} localTransformations:\n  want: {}\n  got:  {}",
                    serde_json::to_string_pretty(
                        want.get("localTransformations").unwrap_or(&Value::Null)
                    )
                    .unwrap(),
                    serde_json::to_string_pretty(
                        got.get("localTransformations").unwrap_or(&Value::Null)
                    )
                    .unwrap(),
                ));
                total_mismatches += 1;
            }

            // ingredients
            if want.get("ingredients") != got.get("ingredients") {
                mismatch_details.push(format!(
                    "{prefix} ingredients:\n  want: {}\n  got:  {}",
                    serde_json::to_string_pretty(
                        want.get("ingredients").unwrap_or(&Value::Null)
                    )
                    .unwrap(),
                    serde_json::to_string_pretty(
                        got.get("ingredients").unwrap_or(&Value::Null)
                    )
                    .unwrap(),
                ));
                total_mismatches += 1;
            }
        }
    }

    if total_mismatches > 0 {
        panic!(
            "Signals golden parity: {total_mismatches} unexpected mismatch(es):\n{}",
            mismatch_details.join("\n")
        );
    }
}
